version: '3.4'

services:
  catalogdb:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build: 
      context: .
      dockerfile: "./Services/Catalog/Catalog.API/Dockerfile"

  redis:
    image: redis:6.2.4-alpine

volumes:
  mongo_data:
  redis_data: