version: '3.4'

services:
  catalogdb:
    image: mongo
    
  basketdb:
    image: redis:6.2.4-alpine
    
  discountdb:
    image: postgres:13-alpine
    
  portainer:
    image: portainer/portainer-ce
    
  pgadmin:
    image: dpage/pgadmin4

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build: 
      context: .
      dockerfile: "./Services/Catalog/Catalog.API/Dockerfile"
    
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: ./Services/Basket/Basket.API
      
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: ./Services/Discount/Discount.API
      
  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: ./Services/Discount/Discount.Grpc

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data: