version: '3.4'

services:
  catalogdb:
    image: mongo
    
  basketdb:
    image: redis:6.2.4-alpine
    
  portainer:
    image: portainer/portainer-ce

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build: 
      context: .
      dockerfile: "./Services/Catalog/Catalog.API/Dockerfile"
    
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: ./Services/Basket/Basket.API

volumes:
  mongo_data:
  portainer_data: