version: '3.4'

services:
  catalogdb:
    image: mongo
    
  redisdb:
    image: redis:6.2.4-alpine

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build: 
      context: .
      dockerfile: "./Services/Catalog/Catalog.API/Dockerfile"
    
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: ./Services/Basket/Basket.API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"

volumes:
  mongo_data: