version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes: 
      - mongo_data:/data/db

  catalog.api:
    container_name: catalog.api
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on: 
      - catalogdb
    ports: 
      - "8000:80"
  
  redis:
    container_name: basket.redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data